name: oracle_client
on:
  push:

jobs:
  oracle_client:
    name: Oracle instant client on macOS
    strategy:
      matrix:
        include:
        - os: macos-14
          url: https://download.oracle.com/otn_software/mac/instantclient/instantclient-basiclite-macos-arm64.dmg
        - os: macos-13
          url: https://download.oracle.com/otn_software/mac/instantclient/instantclient-basiclite-macos.dmg
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Get ETag
      id: get-etag
      run: |
         ETAG=$(wget --method=HEAD --server-response ${{ matrix.url }}  2>&1 | grep ETag | sed -e 's/ *ETag: *//' -e 's/[^A-Za-z0-9]/_/g')
         echo "etag=$ETAG" >> $GITHUB_OUTPUT
    - name: Cache Oracle instant client
      id: cache-oracle-instant-client
      uses: actions/cache@v4
      with:
        path: ~/Downloads/instantclient*
        key: oracle-instant-client-${{ matrix.os }}-${{ steps.get-etag.outputs.etag }}
    - if: ${{ steps.cache-oracle-instant-client.outputs.cache-hit != 'true' }}
      name: install Oracle instant client
      run: |
        curl -Lo instantclient-basiclite.dmg  ${{ matrix.url }}
        hdiutil mount instantclient-basiclite.dmg
        for dir in $(ls -d /Volumes/instantclient-*); do
          pushd $dir
          test -f install_ic.sh && echo "run $dir/install_ic.sh" && ./install_ic.sh
          popd
          hdiutil detach $dir
        done
    - name: check import addresses in Oracle instant client
      run: |
        OCI_DIR=$(ls -d $HOME/Downloads/instantclient*)
        cc -o check-oracle-client test/check-oracle-client.c plthook_osx.c -I. -L$OCI_DIR -Wl,-rpath,$OCI_DIR -lclntsh
        env DYLD_BIND_AT_LAUNCH=1 ./check-oracle-client
